services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prom_data:/docker/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 9091:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=#{grafana-user}
      - GF_SECURITY_ADMIN_PASSWORD=#{grafana-password}
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9092:9092
volumes:
  prom_data: