server:
  port: 9010
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
spring:
  data:
    mongodb:
      uri: 'mongodb+srv://#{mongodb-username}:#{mongodb-password}@cluster0.gzaghmd.mongodb.net/#{mongodb-dbname}?retryWrites=true&w=majority&appName=Cluster0'
logging:
  level:
    org.springframework: error
    org.mongodb: error

project:
  spring:
    username: #{default-username}
    password: #{default-password}