management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

mongodb:
  dbname-auth: ${MONGODB_DB_AUTH}
  dbname-next: ${MONGODB_DB_NEXT}
  uri: 'mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.gzaghmd.mongodb.net/${MONGODB_DBNAME}?retryWrites=true&w=majority&appName=Cluster0'

logging:
  level:
    org.springframework: error
    org.mongodb: error

project:
  spring:
    username: ${SPRING_USERNAME}
    password: ${SPRING_PASSWORD}

logging.level.org.springframework.web: DEBUG